name: Suggestion
description: Suggest an enhancement to make one of our web part samples even better
labels: type:enhancement

body:
- type: markdown
  attributes:
    value: |

      Thank you for your suggestion! Use the sections below to submit a suggestion ONLY if it's related to samples in this repo. If you have an issue or question about the SharePoint Framework or its documentation, please submit it at https://aka.ms/spdev-issues.
      
      - Suggestions that do not follow the below template will automatically be closed
      - All ideas are welcome - let's build something together!
      - This repo is maintained by volunteers (not Microsoft). Please be courteous and patient. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple suggestions please submit them separately so we can track resolution.
      - Screenshots are always helpful (just paste any images right here in the suggestion)

- type: input
  id: sample
  validations:
    required: true
  attributes:
    label: Sample
    description: |
        Which sample are you talking about
        
        Use the sample name or URL. We don't want to be spend all this time diagnosing issues about the wrong sample, do we?
