# Configuration for Label Actions - https://github.com/dessant/label-actions

# Actions taken when the `heated` label is added to issues or pull requests
heated:
  # Post a comment
  comment: >
    The thread has been temporarily locked.
    Please follow our community guidelines.
  # Lock the thread
  lock: true
  # Set a lock reason
  lock-reason: 'too heated'
  # Additionally, add a label to pull requests
  prs:
    label: 'on hold'

# Actions taken when the `heated` label is removed from issues or pull requests
-heated:
  # Unlock the thread
  unlock: true
